name: Check

on:
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/check.yml
      - src/**
      - tests/**
  push:
    branches:
      - main
    paths:
      - .github/workflows/check.yml
      - src/**
      - tests/**
  workflow_dispatch:

env:
  # Specifies whether data about the .NET tools usage is collected and sent to Microsoft.
  DOTNET_CLI_TELEMETRY_OPTOUT: false
  # Controls diagnostics tracing from the hosting components.
  DOTNET_HOST_TRACE: 0
  # Controls the verbosity of diagnostics tracing from the hosting components.
  DOTNET_HOST_TRACE_VERBOSITY: 1
  # Specifies whether .NET welcome and telemetry messages are displayed on the first run.
  DOTNET_NOLOGO: true
  # Specifies the version of the .NET SDK to use.
  DOTNET_VERSION: 10.0.x
  # Name of the shared tests artifact
  TESTS_ARTIFACT_NAME: tests

jobs:

  build:

    env:
      # Name of the configuration to build.
      BUILD_CONFIGURATION_NAME: Release
      # Runtime identifier to build for.
      DOTNET_BUILD_RUNTIME_ID: linux-x64
      # Path to the project file
      MAIN_PROJECT_FILE_PATH: src/System.Utils/System.Utils.csproj
      # Path to the tests project file
      TESTS_PROJECT_FILE_PATH: tests/System.Utils.Tests/System.Utils.Tests.csproj
      # Path to the test project publish directory.
      TESTS_PROJECT_PUBLISH_DIRECTORY_PATH: out

    name: Build

    permissions:
      # Required to checkout the repo
      contents: read

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Setup .NET 10
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore
      run: >-
        dotnet restore ${{ env.TESTS_PROJECT_FILE_PATH }}
        --runtime ${{ env.DOTNET_BUILD_RUNTIME_ID }}

    - name: Build Main
      run: >-
        dotnet build ${{ env.MAIN_PROJECT_FILE_PATH }}
        --configuration ${{ env.BUILD_CONFIGURATION_NAME }}
        --no-restore
        --runtime ${{ env.DOTNET_BUILD_RUNTIME_ID }}

    - name: Publish Tests
      run: >-
        dotnet publish ${{ env.TESTS_PROJECT_FILE_PATH }}
        --configuration ${{ env.BUILD_CONFIGURATION_NAME }}
        --no-restore
        --runtime ${{ env.DOTNET_BUILD_RUNTIME_ID }}
        --self-contained false
        --output ${{ env.TESTS_PROJECT_PUBLISH_DIRECTORY_PATH }}

    - name: Upload Tests
      uses: actions/upload-artifact@v7
      with:
        name: ${{ env.TESTS_ARTIFACT_NAME }}
        path: ${{ env.TESTS_PROJECT_PUBLISH_DIRECTORY_PATH }}

  runUnitTests:

    env:
      # Path to the test results directory relative to the root of the project.
      TESTS_RESULTS_DIRECTORY_NAME: testsResults

    name: Run Unit Tests

    needs: build

    permissions:
      # Required by [EnricoMi/publish-unit-test-result-action]
      checks: write
      # Required by [EnricoMi/publish-unit-test-result-action, marocchino/sticky-pull-request-comment]
      pull-requests: write

    runs-on: ubuntu-latest

    steps:

    - name: Setup .NET 10
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
      env:
        DOTNET_NOLOGO: true

    - name: Download Build
      uses: actions/download-artifact@v4
      with:
        name: ${{ env.TESTS_ARTIFACT_NAME }}

    - name: Run Tests
      run: >-
        dotnet test ./System.Utils.Tests.dll
        --collect:"Code Coverage;Format=Cobertura"
        --filter TestCategory=Unit
        --logger:"trx"
        --results-directory ${{ env.TESTS_RESULTS_DIRECTORY_NAME }}

    - name: Publish Result
      uses: EnricoMi/publish-unit-test-result-action@c950f6fb443cb5af20a377fd0dfaa78838901040 #v2.23.0
      with:
        check_name: Unit Tests
        check_run: false # feature does not work well like at all
        files: |
          ${{ env.TESTS_RESULTS_DIRECTORY_NAME }}/*.trx

    - name: Convert Coverage Report to Markdown
      uses: irongut/CodeCoverageSummary@51cc3a756ddcd398d447c044c02cb6aa83fdae95 #v1.3.0
      with:
        badge: true
        filename: '${{ env.TESTS_RESULTS_DIRECTORY_NAME }}/*/*.cobertura.xml'
        format: markdown
        output: file
        thresholds: '70 75'

    - name: Add Coverage Report to PR
      uses: marocchino/sticky-pull-request-comment@52423e01640425a022ef5fd42c6fb5f633a02728 #v2.9.1
      if: github.event_name == 'pull_request'
      with:
        header: Unit Tests
        recreate: true
        path: code-coverage-results.md

  runIntegrationTests:

    env:
      # Path to the test results directory relative to the root of the project.
      TESTS_RESULTS_DIRECTORY_NAME: testsResults

    name: Run Integration Tests

    needs: build

    permissions:
      # Required by [EnricoMi/publish-unit-test-result-action]
      checks: write
      # Required by [EnricoMi/publish-unit-test-result-action, marocchino/sticky-pull-request-comment]
      pull-requests: write

    runs-on: ubuntu-latest

    steps:

    - name: Setup .NET 10
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
      env:
        DOTNET_NOLOGO: true

    - name: Download Build
      uses: actions/download-artifact@v4
      with:
        name: ${{ env.TESTS_ARTIFACT_NAME }}

    - name: Run Tests
      run: >-
        dotnet test ./System.Utils.Tests.dll
        --collect:"Code Coverage;Format=Cobertura"
        --filter TestCategory=Integration
        --logger:"trx"
        --results-directory ${{ env.TESTS_RESULTS_DIRECTORY_NAME }}

    - name: Publish Result
      uses: EnricoMi/publish-unit-test-result-action@c950f6fb443cb5af20a377fd0dfaa78838901040 #v2.23.0
      with:
        check_name: Integration Tests
        check_run: false # feature does not work well like at all
        files: |
          ${{ env.TESTS_RESULTS_DIRECTORY_NAME }}/*.trx
