name: Check

on:
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/check.yml
      - src/**
      - tests/**
  push:
    branches:
      - main
    paths:
      - .github/workflows/check.yml
      - src/**
      - tests/**
  workflow_dispatch:

permissions:
  checks: write
  contents: read
  pull-requests: write

concurrency:
  group: check-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  BUILD_CONFIGURATION: Release
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_VERBOSITY: minimal
  MAIN_PROJECT_PATH: src/System.Utils/System.Utils.csproj
  TEST_PROJECT_PATH: tests/System.Utils.Tests/System.Utils.Tests.csproj
  TESTS_RESULTS_DIRECTORY_NAME: TestResults

jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 10
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x
          cache: true
          cache-dependency-path: |
            src/System.Utils/System.Utils.csproj
            tests/System.Utils.Tests/System.Utils.Tests.csproj

      - name: Restore
        run: >-
          dotnet restore ${{ env.TEST_PROJECT_PATH }}
          --verbosity ${{ env.DOTNET_VERBOSITY }}

      - name: Build
        run: >-
          dotnet build ${{ env.MAIN_PROJECT_PATH }}
          --configuration ${{ env.BUILD_CONFIGURATION }}
          --no-restore
          --verbosity ${{ env.DOTNET_VERBOSITY }}

      - name: Run Tests
        run: >-
          dotnet test ${{ env.TEST_PROJECT_PATH }}
          --configuration ${{ env.BUILD_CONFIGURATION }}
          --no-build
          --coverage
          --coverage-output-format cobertura
          --report-trx
          --report-trx-filename test-results.trx
          --results-directory ${{ env.TESTS_RESULTS_DIRECTORY_NAME }}
          --verbosity ${{ env.DOTNET_VERBOSITY }}

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: ${{ env.TESTS_RESULTS_DIRECTORY_NAME }}/**/*.trx
          if-no-files-found: error

      - name: Convert Coverage Report to Markdown
        if: always()
        uses: irongut/CodeCoverageSummary@51cc3a756ddcd398d447c044c02cb6aa83fdae95 #v1.3.0
        with:
          badge: true
          filename: "${{ env.TESTS_RESULTS_DIRECTORY_NAME }}/*/*.cobertura.xml"
          format: markdown
          output: file
          thresholds: "70 75"

      - name: Add Coverage Report to PR
        if: always() && github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@52423e01640425a022ef5fd42c6fb5f633a02728 #v2.9.1
        with:
          header: Code Coverage
          recreate: true
          path: code-coverage-results.md
